function w(t){const o=indexedDB.open("chatgpt-bookmarks",1);o.onupgradeneeded=e=>{e.target.result.createObjectStore("bookmarks",{keyPath:"id"}).createIndex("by_conversation","conversationId")},o.onsuccess=e=>{const n=e.target.result;t(n)},o.onerror=e=>{console.error("Failed to open DB",e.target.error)}}function C(t,o,e){const r=t.transaction("bookmarks","readonly").objectStore("bookmarks").index("by_conversation").getAll(IDBKeyRange.only(o));r.onsuccess=()=>{const i=r.result.length;e(`Bookmark ${i+1}`)},r.onerror=()=>{e("Bookmark 1")}}function E(t,{conversationId:o,turnIndex:e,name:n}){const s=`${o}:${e}`;if(n){const l=t.transaction("bookmarks","readwrite");l.objectStore("bookmarks").put({id:s,conversationId:o,turnIndex:e,name:n,createdAt:Date.now()}),l.oncomplete=()=>console.log("Bookmark saved:",n,o,e)}else C(t,o,l=>{const r=t.transaction("bookmarks","readwrite");r.objectStore("bookmarks").put({id:s,conversationId:o,turnIndex:e,name:l,createdAt:Date.now()}),r.oncomplete=()=>console.log("Bookmark saved:",l,o,e)})}function S(t,o,e){const r=t.transaction("bookmarks","readonly").objectStore("bookmarks").index("by_conversation").getAll(IDBKeyRange.only(o));r.onsuccess=()=>{e(r.result)},r.onerror=()=>{e([])}}function L(t,o,e){const s=t.transaction("bookmarks","readwrite").objectStore("bookmarks"),l=s.get(o);l.onsuccess=()=>{const r=l.result;r&&(r.name=e,s.put(r),console.log("Bookmark name updated to:",e))}}function T(){w(t=>{const n=t.transaction("bookmarks","readonly").objectStore("bookmarks").getAll();n.onsuccess=()=>{const s=n.result;console.log("All saved bookmarks:",s);const l=s.reduce((r,i)=>(r[i.conversationId]||(r[i.conversationId]=[]),r[i.conversationId].push(i),r),{});console.log("Bookmarks grouped by conversation:",l)}})}function I(t,o){const e=t.transaction("bookmarks","readwrite");e.objectStore("bookmarks").delete(o),e.oncomplete=()=>{console.log("Bookmark deleted:",o)},e.onerror=s=>{console.error("Error deleting bookmark:",s.target.error)}}window.ChatGPTBookmarks={openBookmarksDB:w,saveBookmark:E,getBookmarksForConversation:S,updateBookmarkName:L,logAllBookmarks:T,deleteBookmark:I};console.log("ChatGPT Bookmark extension loaded!!");const g=`
  <svg width="16" height="22" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <path d="M0,0 h100 v120 l-50,-30 l-50,30 z" fill="#F4A300" />
    <polygon fill="white" points="50,22 58,42 78,42 62,56 68,76 50,64 32,76 38,56 22,42 42,42" />
  </svg>
`,j=`
  <svg xmlns="http://www.w3.org/2000/svg" height="14" width="14" viewBox="0 0 24 24">
    <path fill="none" stroke="#FFA500" stroke-width="2" d="M5 3a2 2 0 0 0-2 2v16l9-4 9 4V5a2 2 0 0 0-2-2H5z"/>
    <path fill="#fff" d="M12 8.5l1.45 2.95 3.25.47-2.35 2.29.56 3.24L12 15.27l-2.91 1.53.56-3.24-2.35-2.29 3.25-.47z"/>
  </svg>
`,f=`
  <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 16 16">
    <polyline points="4 10 8 6 12 10" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
`;function M(){const t=document.createElement("button");Object.assign(t.style,{position:"fixed",top:"56px",right:"20px",background:"white",border:"1px solid #ccc",borderRadius:"6px",padding:"6px",cursor:"pointer",zIndex:"10000",boxShadow:"0 2px 10px rgba(0,0,0,0.1)",display:"flex",alignItems:"center",justifyContent:"center",height:"32px",width:"32px"});let o=!1;t.innerHTML=g,t.title="Show Bookmarks";const e=document.createElement("div");Object.assign(e.style,{position:"fixed",top:"56px",right:"20px",background:"white",border:"1px solid #ccc",borderRadius:"6px",padding:"8px",maxHeight:"70vh",overflowY:"auto",zIndex:"9999",boxShadow:"0 2px 10px rgba(0,0,0,0.1)",minWidth:"180px",fontSize:"13px",display:"none"});const n=document.createElement("h3");n.textContent="Bookmarks",Object.assign(n.style,{margin:"0 0 8px 0",fontSize:"14px",fontWeight:"500"}),e.appendChild(n);const s=document.createElement("div");return s.id="bookmark-list",e.appendChild(s),t.addEventListener("click",()=>{o=e.style.display!=="block",e.style.display=o?"block":"none",t.title=o?"Hide Bookmarks":"Show Bookmarks",t.innerHTML=o?f:g,t.style.border=o?"none":"1px solid #ccc",o?(t.style.backgroundColor="transparent",t.style.boxShadow="none"):(t.style.backgroundColor="white",t.style.boxShadow="0 2px 10px rgba(0,0,0,0.1)")}),document.body.appendChild(t),document.body.appendChild(e),{container:e,toggleBtn:t}}function k(){const t=window.location.pathname.split("/").pop(),o=document.getElementById("bookmark-list"),e=o==null?void 0:o.parentElement,n=document.querySelector('button[title^="Show Bookmarks"],button[title^="Hide Bookmarks"]');!o||!e||!n||window.ChatGPTBookmarks.openBookmarksDB(s=>{window.ChatGPTBookmarks.getBookmarksForConversation(s,t,l=>{if(o.innerHTML="",l.length===0){e.style.display="none",n.innerHTML=g,n.title="Show Bookmarks",n.style.border="1px solid #ccc",n.style.backgroundColor="white";return}e.style.display="block",n.innerHTML=f,n.title="Hide Bookmarks",n.style.border="none",n.style.backgroundColor="transparent",n.style.boxShadow="none",l.slice().sort((r,i)=>r.turnIndex-i.turnIndex).forEach(r=>{const i=document.createElement("div");Object.assign(i.style,{padding:"6px",borderBottom:"1px solid #eee",cursor:"pointer",display:"flex",alignItems:"center",gap:"6px",position:"relative",fontSize:"12px"});const h=document.createElement("div");h.innerHTML=j,i.appendChild(h);const m=document.createElement("span");m.textContent=r.name||`Bookmark ${r.turnIndex}`,m.style.flex="1",i.appendChild(m);const d=document.createElement("div");d.style.display="flex",d.style.alignItems="center",d.style.gap="2px",d.style.marginLeft="6px";const c=document.createElement("button");Object.assign(c.style,{background:"none",border:"none",cursor:"pointer",color:"#888",fontSize:"14px",padding:"2px 4px",display:"none"}),c.innerHTML=`
              <svg xmlns="http://www.w3.org/2000/svg" height="14" width="14" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 16 16">
                <path d="M3 13l2.5-2.5M13 3l-8.5 8.5M11.5 2.5a2.121 2.121 0 1 1 3 3L5 15H2v-3L11.5 2.5z"/>
              </svg>
            `,c.title="Edit bookmark name",d.appendChild(c),c.addEventListener("click",b=>{b.stopPropagation();const a=document.createElement("input");a.type="text",a.value=r.name||`Bookmark ${r.turnIndex}`,a.style.fontSize="12px",a.style.flex="1",a.style.marginLeft="4px",a.style.padding="2px 4px",a.style.border="1px solid #ccc",a.style.borderRadius="3px",i.replaceChild(a,m),a.focus(),a.select();function x(){const u=a.value.trim()||`Bookmark ${r.turnIndex}`;window.ChatGPTBookmarks.openBookmarksDB(v=>{window.ChatGPTBookmarks.updateBookmarkName(v,r.id,u),k()})}a.addEventListener("blur",x),a.addEventListener("keydown",u=>{u.key==="Enter"?a.blur():u.key==="Escape"&&k()})});const p=document.createElement("button");Object.assign(p.style,{background:"none",border:"none",cursor:"pointer",padding:"2px 4px",color:"#666",fontSize:"14px",display:"none"}),p.innerHTML="×",p.title="Delete bookmark",p.id=`delete-bookmark-btn-${r.id}`,d.appendChild(p),i.addEventListener("mouseenter",()=>{c.style.display="block",p.style.display="block"}),i.addEventListener("mouseleave",()=>{c.style.display="none",p.style.display="none"}),i.appendChild(d),i.addEventListener("click",b=>{if(b.target.id===`delete-bookmark-btn-${r.id}`){window.ChatGPTBookmarks.openBookmarksDB(x=>{window.ChatGPTBookmarks.deleteBookmark(x,r.id),k()});return}const a=document.querySelector(`[data-testid="conversation-turn-${r.turnIndex}"]`);a&&(a.scrollIntoView({behavior:"smooth",block:"start"}),a.style.backgroundColor="#fff3cd",setTimeout(()=>{a.style.backgroundColor=""},2e3))}),o.appendChild(i)})})})}M();k();let y=location.href;new MutationObserver(()=>{const t=location.href;t!==y&&(y=t,k())}).observe(document,{subtree:!0,childList:!0});function H(t,o){const e=document.createElement("button");e.className="chatgpt-bookmark-button",e.innerHTML=`
    ${g}&nbsp;Bookmark
  `,Object.assign(e.style,{display:"inline-flex",alignItems:"center",border:"1px solid #ccc",padding:"4px 8px",marginTop:"10px",cursor:"pointer",background:"#fff",borderRadius:"4px",fontSize:"14px",width:"100px",position:"relative"}),e.addEventListener("click",()=>{const n=window.location.pathname.split("/").pop();window.ChatGPTBookmarks.openBookmarksDB(s=>{window.ChatGPTBookmarks.saveBookmark(s,{conversationId:n,turnIndex:o,name:`Response ${o/2}`}),k()})});try{t.appendChild(e)}catch(n){console.error("Failed to append button:",n)}}function B(){document.querySelectorAll("div.group\\/conversation-turn").forEach((o,e)=>{const n=o.closest('article[data-testid^="conversation-turn-"]');if(n){const s=parseInt(n.getAttribute("data-testid").split("-").pop());s%2===0&&(o.querySelector(".chatgpt-bookmark-button")||H(o,s))}})}B();const z=new MutationObserver(t=>{for(const o of t)if(o.addedNodes.length){B();break}});z.observe(document.body,{childList:!0,subtree:!0});
//# sourceMappingURL=content.js.map
